library(ggplot2)
library(lattice)
library(plyr)
library(Rmisc)
library(reshape2)
library(plot3D)
library(scales)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(chorddiag)
library(ggpubr)
library(cowplot)
library(MikkoVihtakari/PlotSvalbard)
library(car)
library(dplyr)
library("tidyverse")
library(ggridges)
library("naniar")
library("ggplot2movies")
library(forcats)


install.packages("ggplot2movies")
install.packages("naniar")
install.packages("ggridges")
install.packages("dplyr")
 remove.packages("rlang")
 install.packages("rlang")
 ?reshape
 